version: '3.7'

services:
  abp_7_2-angular:
    image: mycompanyname/abp_7_2-angular:latest
    container_name: abp_7_2-angular
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - abp_7_2-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  abp_7_2-api:
    image: mycompanyname/abp_7_2-api:latest
    container_name: abp_7_2-api
    hostname: abp_7_2-api
    build:
      context: ../../
      dockerfile: src/ABP_7_2.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://abp_7_2-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44354
      - App__RedirectAllowedUrls=http://localhost:4200
      - App__MVCPublicUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ABP_7_2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  

  abp_7_2-web-public:
    image: mycompanyname/abp_7_2-web-public:latest
    container_name: abp_7_2-web-public
    build:
      context: ../../
      dockerfile: src/ABP_7_2.Web.Public/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44306
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsContainerized=true      
      - RemoteServices__Default__BaseUrl=http://abp_7_2-api
      - AuthServer__Authority=https://localhost:44354/
      - AuthServer__MetaAddress=http://abp_7_2-api
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ABP_7_2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44306:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network  
  db-migrator:
    image: mycompanyname/abp_7_2-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/ABP_7_2.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__ABP_7_2_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__ABP_7_2_Swagger__RootUrl=https://localhost:44354
      - OpenIddict__Applications__ABP_7_2_Web_Public__RootUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ABP_7_2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  sqldata:
    name: abp_7_2_sqldata
networks:
  abp-network:
    name: abp_7_2-network
    driver: bridge
